component_depth: 3
languages:
- csharp
exclude:
- /Assets/Asset Store/.*
- /Assets/_Scripts/Helpers/Array2DEditor/.*
- /Assets/Plugins/.*
- /Assets/_Scripts/Editor/.*
- /Assets/_Scripts/MyEditor/Attributes/.*