// <auto-generated/>
// ReSharper disable All
using UnityEngine;

namespace EasyButtons
{
	using System.Diagnostics.CodeAnalysis;

	[ExcludeFromCodeCoverage]
    public class CustomEditorButtonsExample : MonoBehaviour
    {
        [Button("Custom Editor Example")]
        private void SayHello()
        {
            Debug.Log("Hello from custom editor");
        }
    }
}
